apiVersion: v1
kind: Service
metadata:
  name: platformtservice-srv
spec: 
  type: NodePort
  selector:
    app: platformservice
  ports:
    - name: platformservice
      protocol: TCP
      port: 5202
      targetPort: 5202